### ISSUE TITLE
Need OR operation in REQUIRES block

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/CryptSL#11]
For the below rule, our analysis expects both the predicates for parameter named `params` namely 
*generatedRSAKeyParameters* and *generatedRSAPrivateCrtKeyParameters*. But in reality we actually need either public or private key based on the value of `is_encryption` flag.

```
SPEC org.bouncycastle.crypto.engines.RSAEngine

OBJECTS
	org.bouncycastle.crypto.CipherParameters params;
	
	boolean is_encryption;
	byte[] cipherText;
	
EVENTS
	c : RSAEngine();
	
	i : init(is_encryption, params);
	
	p : cipherText = processBlock(_, _, _);
	
ORDER
	c, (i, p)+
	
REQUIRES
	// Problem : analysis expects both these predicates for params
	generatedRSAKeyParameters[params];
	generatedRSAPrivateCrtKeyParameters[params];

	// What is required
	generatedRSAKeyParameters[params] || generatedRSAPrivateCrtKeyParameters[params];
	
	// What is currently done
	generatedRSAKeyParametersOrRSAPrivateCrtKeyParameters[params];

ENSURES
	generatedRSAEngine[this] after c;
	encrypted[cipherText] after p;
```

**Comment by johspaeth** [comment]
Same for the one below. 

Any of the two examples below are valid uses. In `example1` variable `ECPublicKeyParameters pubKey` directly flows to the call `encryptor.init(pubKey);`. Alternatively, one can also wrap `pubKey` in a `ParametersWithRandom` object and pass this one into the encryptor (`encryptor.init(parRand);`) as implemented in `example2`.

```
public void example1(String point) {
	ECDomainParameters params = new ECDomainParameters(Constants.curve, Constants.curve.decodePoint(Hex.decode(point)), Constants.n);
	ECPublicKeyParameters pubKey = new ECPublicKeyParameters(Constants.curve.decodePoint(Hex.decode(point)), params);
	ECPoint data = pubKey.getParameters().getG().multiply(Constants.n);
	ECElGamalEncryptor encryptor = new ECElGamalEncryptor();
	encryptor.init(pubKey);
	ECPair cipherText = encryptor.encrypt(data);
}
	
public void example2(String point) {
	ECDomainParameters params = new ECDomainParameters(Constants.curve, Constants.curve.decodePoint(Hex.decode(point)), Constants.n);
	ECPublicKeyParameters pubKey = new ECPublicKeyParameters(Constants.curve.decodePoint(Hex.decode(point)), params);
	ParametersWithRandom parRand = new ParametersWithRandom(pubKey, new SecureRandom());
	ECPoint data = pubKey.getParameters().getG().multiply(Constants.n);
	ECElGamalEncryptor encryptor = new ECElGamalEncryptor();
	encryptor.init(parRand);
	ECPair cipherText = encryptor.encrypt(data);
}
```

To be able to express these pattern in CrySL we need an OR clause

```
REQUIRES
	generatedECPublicKeyParameters[params] OR generatedParametersWithRandom[params];
```
*Note: It is not well-defined when we use a predicate with mutliple parameters.
`generatedECPublicKeyParameters[params,key] OR generatedParametersWithRandom[params,p];` wouldn't make any sense. We have to disallow this or reconsider the parameters of a predicate in general. *

**Comment by rakshitkr** [comment]
@kruegers The implementation works perfectly while OR-ing two required predicates. I've modified all BC rules to accommodate this enhancement in this[https://github.com/CROSSINGTUD/Crypto-API-Rules/commit/2504eea79b0a2c1665597c9fe3b829bbef27f1d8] commit. this Could you generalize the above implementation for OR-ing three predicates?

**Comment by kruegers** [comment]
Will do. Thanks for testing.

**Comment by kruegers** [comment]
@rakshitkr OR-ing predicates should now work for more than two predicates as well. Can you please test again?

**Comment by rakshitkr** [comment]
@kruegers The testing of OR-ing 3 predicates is already done. Kindly close this issue. Thanks in advance!
