### ISSUE TITLE
Introduce shorthands for some part(...) predicates.

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CryptSL#16]
In the rule for javax.crypto.Cipher, the part predicate is used several times to fetch different parts of the transformation argument in Cipher.getInstance(transformation). The syntax for it is quite verbose and (potentially?) confusing. Introduce syntactic sugar that maps to the existing part() expressions as follows:
alg(transformation) <=> [part(0, "/", transformation)](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/Cipher.cryptsl#L74)
mode(transformation) <=> [part(1, "/", transformation)](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/Cipher.cryptsl#L85)
pad(transformation) <=> [part(2, "/", transformation)](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/Cipher.cryptsl#L83)

After extending CrySL, please also update the Cipher rule accordingly.

**Comment by johspaeth** [comment]
Wouldn't it even make sense to define these terms in the OBJECTS section rather than in the CONSTRAINTS section? Something like:

```
OBJECTS
    int keySize;
    String transformation;
    String algorithm = part(0,"/", transformation);
    String mode = part(0,"/", transformation);
```

**Comment by kruegers** [comment]
I get where you are coming from, but I would rather not introduce assignments in the objects section. First, because people might try assigning values there as well, like int keysize = {128, 192, 256} or something like that. Second, we would still leave it to the users to handle (this particular) part() predicate(s) and I was aiming for avoiding exactly that. That said, IIRC, @rbonifacio's extensions introduce something similar. 

Are you okay with implementing the syntactic sugar first and then discuss the matter again once we merge Rodrigo's work back into CrySL, @johspaeth?

**Comment by johspaeth** [comment]
Could the grammar disallow int keysize = {128, 192, 256}? 
Looking at the Cipher rule, it could drastically simplify the notation.

Sure, the syntactic sugar is unrelated and can be implemented anyway.
